//
// Created by hassan on 1/1/19.
//

#ifndef CPP_BOARD_GAME_ENGINE_PIECECOORDINATES_H
#define CPP_BOARD_GAME_ENGINE_PIECECOORDINATES_H


class PieceCoordinates {

};


#endif //CPP_BOARD_GAME_ENGINE_PIECECOORDINATES_H
