//
// Created by hassan on 1/1/19.
//

#ifndef CPP_BOARD_GAME_ENGINE_BOARDGAMEOBJECT_H
#define CPP_BOARD_GAME_ENGINE_BOARDGAMEOBJECT_H


class BoardGameObject {

};


#endif //CPP_BOARD_GAME_ENGINE_BOARDGAMEOBJECT_H
